removed rebalance threshold from minter added developer helpers to the deploy script added grantRoles to deploy

diff --git a/script/deploy-minter b/script/deploy-minter
--- a/script/deploy-minter
+++ b/script/deploy-minter
@@ -5,7 +5,10 @@ log "deploying minter $*"
 
 THIS="${BASH_SOURCE[0]}"
 
-MOCK_PRICE=false
+# developer settings
+MOCK_PRICE=""
+DEVELOPER="$PUBLIC_KEY"
+
 # BURN_SIG can be one of
 # - "burn(uint256)"
 #    this works for BaoUSD and is common for other ERC20 tokens. It is the lowest common denominator and
@@ -17,15 +20,33 @@ MOCK_PRICE=false
 # - "burnFrom(address,uint256)"
 #    this is one of the most gas efficient forms, is extensively used and frequetly alongside the burn(uint256) form
 BURN_SIG="burn(uint256)"
+
 while [[ $# -gt 0 ]]; do
   case "$1" in
   --burn-sig)
     BURN_SIG="$2"
+    record "arguments.burn-sig" "${BURN_SIG}"
     shift 2
     ;;
   --mock-price)
-    MOCK_PRICE=true
-    shift
+    MOCK_PRICE="$2"
+    shift 2
+    record "arguments.mockPrice" "${MOCK_PRICE}"
+    ;;
+  --developer)
+    DEVELOPER="$2"
+    record "arguments.developer" "${DEVELOPER}"
+    shift 2
+    ;;
+  --developer-roles)
+    if [[ $RPC_URL == "local" ]]; then
+      DEVELOPER_ROLES="$2"
+      record "arguments.developer-roles" "${DEVELOPER_ROLES}"
+      record "arguments.developer" "${DEVELOPER}"
+    else
+      error "can only use --developer-roles with --rpc-url [local|anvil]"
+    fi
+    shift 2
     ;;
   -*)
     error "unexpected option for ${THIS}: $1"
@@ -38,15 +59,13 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-record "${MOCK_PRICE}" "arguments.mockPrice"
-
 ###################################################################################################
 # read the already deployed addresses
 ###################################################################################################
 
 # shellcheck disable=SC2154 # PUBLIC_KEY is exported elsewhere
 # TODO: make these work without adding .address
-record "${PUBLIC_KEY}" deployer.address
+record deployer.address "${PUBLIC_KEY}"
 record_from_network owner.address baomultisig.address
 record_from_network treasury.address safeGov.address
 
@@ -72,7 +91,7 @@ deploy_contract Stem_v1 "lib/bao-base/src/Stem_v1.sol:Stem_v1" "--constructor-ar
 ###################################################################################################
 
 deploy_stemmed leveragedToken
-deploy_stemmed StakedETHWrappedPriceOracle
+deploy_stemmed stakedETHWrappedPriceOracle
 deploy_stemmed feeReceiver
 deploy_stemmed stabilityPoolManager
 deploy_stemmed reservePool
@@ -91,13 +110,11 @@ deploy_contract LeveragedToken_v1 "src/minter/LeveragedToken_v1.sol:LeveragedTok
 
 peggedSymbol=$(query peggedToken.symbol)
 collateralSymbol=$(query collateralToken.symbol)
-record "steamed${collateralSymbol}-${peggedSymbol}" leveragedToken.symbol
-record "Bao Zhenglong steamed ${collateralSymbol}-${peggedSymbol}" leveragedToken.name
+record leveragedToken.symbol "steamed${collateralSymbol}-${peggedSymbol}"
+record leveragedToken.name "Bao Zhenglong steamed ${collateralSymbol}-${peggedSymbol}"
 
 upgrade_proxy leveragedToken LeveragedToken_v1 \
   "initialize(address,string,string)" owner leveragedToken.name leveragedToken.symbol
-
-record_from_call leveragedToken.MINTER_ROLE leveragedToken "MINTER_ROLE()(uint256)"
 
 # priceOracle
 # -----------
@@ -111,16 +128,31 @@ deploy_contract StakedETHWrappedPriceOracle_v1 "src/price/StakedETHWrappedPriceO
   --libraries PriceOracle_v1 \
   --constructor-args collateralToken.priceFeed.usd wrappedCollateralToken 3600 300 300 300
 
-upgrade_proxy StakedETHWrappedPriceOracle StakedETHWrappedPriceOracle_v1 "initialize(address)" owner
+upgrade_proxy stakedETHWrappedPriceOracle StakedETHWrappedPriceOracle_v1 "initialize(address)" owner
 
-# TODO: make these work wiythout adding .address
+# TODO: make these work without adding .address
 local priceOracle
-if [[ ${MOCK_PRICE} == true ]]; then
-  priceOracle=$(query MockWrappedPriceOracle.address)
+if [[ -n "${MOCK_PRICE}" ]]; then
+  to_wei() {
+    bc -l <<<"scale=0; (${1} * 10^18 + 0.5)/1"
+  }
+  priceOracle=MockWrappedPriceOracle.address
+  if [[ "${MOCK_PRICE}" != "default" ]]; then
+    local price="${MOCK_PRICE%%,*}"
+    record MockWrappedPriceOracle.price "${price}"
+    price=$(to_wei "${price}") || error "failed to convert price ${price} to wei"
+    record MockWrappedPriceOracle.priceInWei "${price}"
+    local rate="${MOCK_PRICE#*,}"
+    record MockWrappedPriceOracle.rate "${rate}"
+    rate=$(to_wei "${rate}") || error "failed to convert rate ${rate} to wei"
+    record MockWrappedPriceOracle.rateInWei "${rate}"
+    send_transaction MockWrappedPriceOracle "setLatestAnswer(uint256,uint256)" "${price}" "${rate}"
+  fi
+  warn "using mock price oracle: ${priceOracle}"
 else
-  priceOracle=$(query StakedETHWrappedPriceOracle.address)
+  priceOracle=stakedETHWrappedPriceOracle.address
 fi
-record "${priceOracle}" priceOracle.address
+record priceOracle.address "${priceOracle}"
 
 # token distribution
 #####################
@@ -140,8 +172,6 @@ upgrade_proxy feeReceiver TokenDistributor_v1 "initialize(address,string)" owner
 deploy_contract ReservePool_v1 "src/minter/ReservePool_v1.sol:ReservePool_v1"
 upgrade_proxy reservePool ReservePool_v1 "initialize(address)" owner
 
-record_from_call ReservePool_v1.REQUESTER_ROLE reservePool "REQUESTER_ROLE()(uint256)"
-
 # minter
 # ------
 deploy_library Config_v1 src/minter/lib/Config_v1.sol:Config_v1
@@ -152,15 +182,14 @@ deploy_contract Minter_v1 src/minter/Minter_v1.sol:Minter_v1 \
 
 upgrade_proxy minter Minter_v1 "initialize(address)" owner
 
-record_from_call Minter_v1.ZERO_FEE_ROLE minter "ZERO_FEE_ROLE()(uint256)"
-record_from_call Minter_v1.HARVESTER_ROLE minter "HARVESTER_ROLE()(uint256)"
+grantRoles minter leveragedToken.MINTER_ROLE
+grantRoles minter reservePool.REQUESTER_ROLE
 
-send_transaction minter "grantRoles(address,uint256)" owner Minter_v1.ZERO_FEE_ROLE
-send_transaction leveragedToken "grantRoles(address,uint256)" minter leveragedToken.MINTER_ROLE
-send_transaction reservePool "grantRoles(address,uint256)" minter ReservePool_v1.REQUESTER_ROLE
+send_transaction minter "updatePriceOracle(address)" priceOracle
+send_transaction minter "updateFeeReceiver(address)" feeReceiver
+send_transaction minter "updateReservePool(address)" reservePool
 
 # TODO: set up the minter config
-# TODO: set up the price oracle
 
 # stability pools
 #################
@@ -170,16 +199,12 @@ send_transaction reservePool "grantRoles(address,uint256)" minter ReservePool_v1
 deploy_contract StabilityPool_v1Collateral "src/minter/StabilityPool_v1.sol:StabilityPool_v1" \
   --constructor-args minter wrappedCollateralToken
 upgrade_proxy stabilityPoolCollateral StabilityPool_v1Collateral "initialize(address)" owner
-record_from_call StabilityPool_v1Collateral.REBALANCER_ROLE stabilityPoolCollateral "REBALANCER_ROLE()(uint256)"
-record_from_call StabilityPool_v1Collateral.REWARDER_ROLE stabilityPoolCollateral "REWARDER_ROLE()(uint256)"
 
 # stabilityPoolSteamed
 # --------------------
 deploy_contract StabilityPool_v1Steamed "src/minter/StabilityPool_v1.sol:StabilityPool_v1" \
   --constructor-args minter leveragedToken
 upgrade_proxy stabilityPoolSteamed StabilityPool_v1Steamed "initialize(address)" owner
-record_from_call StabilityPool_v1Steamed.REBALANCER_ROLE stabilityPoolSteamed "REBALANCER_ROLE()(uint256)"
-record_from_call StabilityPool_v1Steamed.REWARDER_ROLE stabilityPoolSteamed "REWARDER_ROLE()(uint256)"
 
 # StabilityPoolManager
 # --------------------
@@ -187,22 +212,33 @@ deploy_contract StabilityPoolManager_v1 "src/minter/StabilityPoolManager_v1.sol:
   --constructor-args minter treasury stabilityPoolCollateral stabilityPoolSteamed
 upgrade_proxy stabilityPoolManager StabilityPool_v1Steamed "initialize(address)" owner
 
-send_transaction stabilityPoolCollateral "grantRoles(address,uint256)" stabilityPoolManager StabilityPool_v1Collateral.REBALANCER_ROLE
-send_transaction stabilityPoolCollateral "grantRoles(address,uint256)" stabilityPoolManager StabilityPool_v1Collateral.REWARDER_ROLE
+grantRoles stabilityPoolManager stabilityPoolCollateral.REBALANCER_ROLE
+grantRoles stabilityPoolManager stabilityPoolCollateral.REWARDER_ROLE
 
-send_transaction stabilityPoolSteamed "grantRoles(address,uint256)" stabilityPoolManager StabilityPool_v1Steamed.REBALANCER_ROLE
-send_transaction stabilityPoolSteamed "grantRoles(address,uint256)" stabilityPoolManager StabilityPool_v1Steamed.REWARDER_ROLE
+grantRoles stabilityPoolManager stabilityPoolSteamed.REBALANCER_ROLE
+grantRoles stabilityPoolManager stabilityPoolSteamed.REWARDER_ROLE
 
-send_transaction minter "grantRoles(address,uint256)" stabilityPoolManager Minter_v1.HARVESTER_ROLE
+grantRoles stabilityPoolManager minter.HARVESTER_ROLE
 
 # genesis
 #########
 deploy_contract Genesis_v1 "src/minter/Genesis_v1.sol:Genesis_v1" --constructor-args minter
 upgrade_proxy genesis Genesis_v1 "initialize(address)" owner
-send_transaction minter "grantRoles(address,uint256)" genesis Minter_v1.ZERO_FEE_ROLE
+grantRoles genesis minter.ZERO_FEE_ROLE
 
 # TODO: set the reward amount
 # TODO: and fill the liquidator with those tokens
+
+###################################################################################################
+# developer options
+###################################################################################################
+if [[ -n "${DEVELOPER_ROLES}" ]]; then
+  record developer.address "${DEVELOPER}"
+  for role in ${DEVELOPER_ROLES//,/ }; do
+    info "granting ${role} to developer ${DEVELOPER}."
+    grantRoles developer "${role}" || warn "failed to grant ${role} to developer ${DEVELOPER}, continuing anyway"
+  done
+fi
 
 ###################################################################################################
 # upgrade the proxies with implementations
@@ -216,3 +252,5 @@ send_transaction stabilityPoolCollateral "transferOwnership(address)" owner
 send_transaction stabilityPoolSteamed "transferOwnership(address)" owner
 send_transaction stabilityPoolManager "transferOwnership(address)" owner
 send_transaction genesis "transferOwnership(address)" owner
+
+log "deployed minter successfully."
